# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import client_handler_pb2 as client__handler__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_handler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_stream(
                '/client_handler.ClientHandler/GetStatus',
                request_serializer=client__handler__pb2.GetRequest.SerializeToString,
                response_deserializer=client__handler__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetConnectConfig = channel.unary_stream(
                '/client_handler.ClientHandler/GetConnectConfig',
                request_serializer=client__handler__pb2.GetRequest.SerializeToString,
                response_deserializer=client__handler__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.GetConnectQR = channel.unary_stream(
                '/client_handler.ClientHandler/GetConnectQR',
                request_serializer=client__handler__pb2.GetRequest.SerializeToString,
                response_deserializer=client__handler__pb2.ConfigResponse.FromString,
                _registered_method=True)


class ClientHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectQR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=client__handler__pb2.GetRequest.FromString,
                    response_serializer=client__handler__pb2.StatusResponse.SerializeToString,
            ),
            'GetConnectConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.GetConnectConfig,
                    request_deserializer=client__handler__pb2.GetRequest.FromString,
                    response_serializer=client__handler__pb2.ConfigResponse.SerializeToString,
            ),
            'GetConnectQR': grpc.unary_stream_rpc_method_handler(
                    servicer.GetConnectQR,
                    request_deserializer=client__handler__pb2.GetRequest.FromString,
                    response_serializer=client__handler__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client_handler.ClientHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('client_handler.ClientHandler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/client_handler.ClientHandler/GetStatus',
            client__handler__pb2.GetRequest.SerializeToString,
            client__handler__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/client_handler.ClientHandler/GetConnectConfig',
            client__handler__pb2.GetRequest.SerializeToString,
            client__handler__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectQR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/client_handler.ClientHandler/GetConnectQR',
            client__handler__pb2.GetRequest.SerializeToString,
            client__handler__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
