# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_handler.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_handler.proto',
  package='client_handler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63lient_handler.proto\x12\x0e\x63lient_handler\"\"\n\nGetRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"n\n\x0eStatusResponse\x12\"\n\x03\x61\x63k\x18\x01 \x01(\x0b\x32\x13.client_handler.AckH\x00\x12,\n\x04info\x18\x02 \x01(\x0b\x32\x1c.client_handler.InfoResponseH\x00\x42\n\n\x08response\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x0cInfoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0e\n\x06output\x18\x02 \x01(\t\"d\n\x0e\x43onfigResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x06output\x18\x02 \x01(\tH\x00\x12&\n\x05image\x18\x03 \x01(\x0b\x32\x15.client_handler.ImageH\x00\x42\x08\n\x06\x63onfig\"\x1b\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x32\x80\x02\n\rClientHandler\x12K\n\tGetStatus\x12\x1a.client_handler.GetRequest\x1a\x1e.client_handler.StatusResponse\"\x00\x30\x01\x12R\n\x10GetConnectConfig\x12\x1a.client_handler.GetRequest\x1a\x1e.client_handler.ConfigResponse\"\x00\x30\x01\x12N\n\x0cGetConnectQR\x12\x1a.client_handler.GetRequest\x1a\x1e.client_handler.ConfigResponse\"\x00\x30\x01\x62\x06proto3'
)




_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='client_handler.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='client_handler.GetRequest.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=74,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='client_handler.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='client_handler.StatusResponse.ack', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='client_handler.StatusResponse.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='client_handler.StatusResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=76,
  serialized_end=186,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='client_handler.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='client_handler.Ack.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=210,
)


_INFORESPONSE = _descriptor.Descriptor(
  name='InfoResponse',
  full_name='client_handler.InfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='client_handler.InfoResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='client_handler.InfoResponse.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=258,
)


_CONFIGRESPONSE = _descriptor.Descriptor(
  name='ConfigResponse',
  full_name='client_handler.ConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='client_handler.ConfigResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='client_handler.ConfigResponse.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='client_handler.ConfigResponse.image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='client_handler.ConfigResponse.config',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=260,
  serialized_end=360,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='client_handler.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='client_handler.Image.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=389,
)

_STATUSRESPONSE.fields_by_name['ack'].message_type = _ACK
_STATUSRESPONSE.fields_by_name['info'].message_type = _INFORESPONSE
_STATUSRESPONSE.oneofs_by_name['response'].fields.append(
  _STATUSRESPONSE.fields_by_name['ack'])
_STATUSRESPONSE.fields_by_name['ack'].containing_oneof = _STATUSRESPONSE.oneofs_by_name['response']
_STATUSRESPONSE.oneofs_by_name['response'].fields.append(
  _STATUSRESPONSE.fields_by_name['info'])
_STATUSRESPONSE.fields_by_name['info'].containing_oneof = _STATUSRESPONSE.oneofs_by_name['response']
_CONFIGRESPONSE.fields_by_name['image'].message_type = _IMAGE
_CONFIGRESPONSE.oneofs_by_name['config'].fields.append(
  _CONFIGRESPONSE.fields_by_name['output'])
_CONFIGRESPONSE.fields_by_name['output'].containing_oneof = _CONFIGRESPONSE.oneofs_by_name['config']
_CONFIGRESPONSE.oneofs_by_name['config'].fields.append(
  _CONFIGRESPONSE.fields_by_name['image'])
_CONFIGRESPONSE.fields_by_name['image'].containing_oneof = _CONFIGRESPONSE.oneofs_by_name['config']
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['InfoResponse'] = _INFORESPONSE
DESCRIPTOR.message_types_by_name['ConfigResponse'] = _CONFIGRESPONSE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.Ack)
  })
_sym_db.RegisterMessage(Ack)

InfoResponse = _reflection.GeneratedProtocolMessageType('InfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFORESPONSE,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.InfoResponse)
  })
_sym_db.RegisterMessage(InfoResponse)

ConfigResponse = _reflection.GeneratedProtocolMessageType('ConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGRESPONSE,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.ConfigResponse)
  })
_sym_db.RegisterMessage(ConfigResponse)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'client_handler_pb2'
  # @@protoc_insertion_point(class_scope:client_handler.Image)
  })
_sym_db.RegisterMessage(Image)



_CLIENTHANDLER = _descriptor.ServiceDescriptor(
  name='ClientHandler',
  full_name='client_handler.ClientHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=392,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='client_handler.ClientHandler.GetStatus',
    index=0,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetConnectConfig',
    full_name='client_handler.ClientHandler.GetConnectConfig',
    index=1,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_CONFIGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetConnectQR',
    full_name='client_handler.ClientHandler.GetConnectQR',
    index=2,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_CONFIGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTHANDLER)

DESCRIPTOR.services_by_name['ClientHandler'] = _CLIENTHANDLER

# @@protoc_insertion_point(module_scope)
